import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { LayoutProvider } from "@/providers/layout-provider";
import { getServerSession } from "next-auth";
import ClientLayout from "./client-layout";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession()
  
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        {session ? (
          <ClientLayout session={session}>
            <LayoutProvider>
              {children}
            </LayoutProvider>
          </ClientLayout>
        ) : (
          <LayoutProvider>
               <p>Or handle the null case as needed</p>
              {children}
          </LayoutProvider>
        )}
      </body>
    </html>
  );
}
